g++ -o ../config.o -c ../config.cpp -std=c++11

g++ test_config.cpp -lcppunit -o test_config -std=c++11 ../config.o ../sniffing/parser.o ../persistance/measure_data.o ../sniffing/headers/ethernet.o ../sniffing/headers/ipv4.o ../sniffing/headers/vxlan.o ../sniffing/headers/measure_header.o ../sniffing/headers/measure_option.o ../sniffing/headers/udp.o
